services:

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    tty: true
    environment:
      MYSQL_DATABASE: full_cycle
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - db-network

  nginx:
    image: nginx:1.23.3-alpine-slim
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  app:
    build: ./node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- npm start
    volumes:
      - ./node:/app
      - /app/node_modules
    networks:
      - app-network
      - db-network
    depends_on:
      - db
    tty: true

networks:
  db-network:
    driver: bridge
  app-network:
    driver: bridge
